src/query/point/mod.rs, src/query/point/point_cone.rs, src/query/point/point_cylinder.rs, src/query/point/point_support_map.rs
This makes the projection of a point on a cone or a cylinder much more accurate and faster.
=> Add special cases for the projection of a point on a cone or a cylinder.

src/bounding_volume/aabb.rs, src/query/point/mod.rs, src/query/point/point_cone.rs, src/query/point/point_cylinder.rs, src/query/point/point_support_map.rs, src/transformation/to_trimesh/cuboid_to_trimesh.rs
This adds a few utilities for AABBs:
- `AABB::vertices` to get an array containing its vertices.
- `AABB::split_at_center` to split an AABB into 4 (in 2D) or 8 (in 3D) parts.
- `AABB::to_trimesh` to compute the mesh representation of an AABB.
=> Aabb utilities

CHANGELOG.md, build/parry2d-f64/Cargo.toml, build/parry2d/Cargo.toml, build/parry3d-f64/Cargo.toml, build/parry3d/Cargo.toml
- Add the `Shape::as_typed_shape` method to convert the shape trait-object
to an enum.
- Add the `TypedShape` enum with variants containing references to concrete shapes
(except for user-defined custom shapes).
- Add dedicated algorithms for the projection of a point on a cone or a cylinder.
- Improve the overall shape serialization performance.
- Add `AABB::vertices` to get an array containing its vertices.
- Add `AABB::split_at_center` to split an AABB into 4 (in 2D) or 8 (in 3D) parts.
- Add `AABB::to_trimesh` to compute the mesh representation of an AABB.
- Remove the `Shape::as_serialize` method.
- Fix a bug causing making some ball/convex shape contact manifold computation
fail when they are penetrating deeply.
=> Release v0.2.0

build/parry2d/examples/time_of_impact_query2d.rs, build/parry2d/tests/geometry/ball_ball_toi.rs, build/parry2d/tests/geometry/time_of_impact2.rs, build/parry3d/examples/time_of_impact_query3d.rs, build/parry3d/tests/geometry/ball_ball_toi.rs, build/parry3d/tests/geometry/ball_triangle_toi.rs, build/parry3d/tests/geometry/still_objects_toi.rs, build/parry3d/tests/geometry/time_of_impact3.rs, build/parry3d/tests/geometry/trimesh_trimesh_toi.rs, src/query/default_query_dispatcher.rs, src/query/gjk/gjk.rs, src/query/nonlinear_time_of_impact/nonlinear_rigid_motion.rs, src/query/query_dispatcher.rs, src/query/time_of_impact/time_of_impact.rs, src/query/time_of_impact/time_of_impact_ball_ball.rs, src/query/time_of_impact/time_of_impact_composite_shape_shape.rs, src/query/time_of_impact/time_of_impact_halfspace_support_map.rs, src/query/time_of_impact/time_of_impact_support_map_support_map.rs
Fix #19 
In addition this removes the `target_dist` argument. That argument results in a significant amount of complexity in the general case, and is prone to return a result that is less accurate. So I think it's best to remove it as it will be set to 0.0 most of the time anyways.
=> Fix linear TOI computation when the first shape is rotated + remove target_dist argument

src/query/closest_points/closest_points_cuboid_cuboid.rs, src/query/contact_manifolds/contact_manifolds_halfspace_pfm.rs, src/query/epa/epa3.rs
Those seems to be for debugging purposes.
Consider using `tracing` crate for filterable logs which user can enable and disable as needed.
=> Comment out print statements

src/shape/shape.rs, src/transformation/to_polyline/cuboid_to_polyline.rs
This makes the `ShapeType` enum usable as a `HashMap` key.
This also includes an unrelated small changes: the order of vertices output by `Cuboid::to_polyline` has been modified as it was invalid before (it did not represent the boundary of the cuboid as it included its diagonal).
=> Make ShapeType hashable

src/query/contact/contact_ball_convex_polyhedron.rs, src/shape/convex_polygon.rs, src/shape/convex_polyhedron.rs, src/shape/cuboid.rs, src/shape/segment.rs, src/shape/shape.rs, src/shape/triangle.rs
`query::contact` could return `None` in cases where the center of the ball lies on the boundary of the shape.
Fix #34
=> Fix edge case for the contact between various convex shapes vs. ball

src/partitioning/qbvh.rs
QBVH traversal panics when `nodes` is empty. I add a check to prevent a panic.
=> Fix QBVH crash when nodes are empty

src/query/time_of_impact/time_of_impact.rs
This caught me by surprise. For future work, we might consider adjusting the TOI query interface such that the `Penetrating` case doesn't return data at all.
=> Clarify semantics of TOI members in Penetrating status

src/bounding_volume/aabb.rs, src/partitioning/mod.rs, src/partitioning/qbvh.rs, src/query/closest_points/closest_points_composite_shape_shape.rs, src/query/contact/contact_composite_shape_shape.rs, src/query/contact_manifolds/contact_manifolds_composite_shape_composite_shape.rs, src/query/contact_manifolds/contact_manifolds_composite_shape_shape.rs, src/query/contact_manifolds/contact_manifolds_heightfield_composite_shape.rs, src/query/contact_manifolds/contact_manifolds_trimesh_shape.rs, src/query/distance/distance_composite_shape_shape.rs, src/query/intersection_test/intersection_test_composite_shape_shape.rs, src/query/nonlinear_time_of_impact/nonlinear_time_of_impact_composite_shape_shape.rs, src/query/nonlinear_time_of_impact/nonlinear_time_of_impact_support_map_support_map.rs, src/query/point/point_composite_shape.rs, src/query/ray/ray_composite_shape.rs, src/query/ray/ray_support_map.rs, src/query/time_of_impact/time_of_impact_composite_shape_shape.rs, src/shape/composite_shape.rs, src/shape/compound.rs, src/shape/polyline.rs, src/shape/trimesh.rs, src/utils/hashable_partial_eq.rs, src/utils/interval.rs, src/utils/mod.rs
This adds various utilities I found useful for some geometric operations:
- Add a method to reverse the order of a polyline.
- Add a method to remove duplicate vertices form a `TriMesh` (and adjusting the index buffer accordingly).
- Add a method to iterate through all the lean data stored by a QBVH.
- Implement the Interval Newton Method for computing all the roots of a non-linear scalar function.
- Implement the intersection test between a spiral and an AABB.
- Rename all occurrences of `quadtree` to `qbvh`. Using the term `quadtree` was not representative of the actual acceleration structure being used (which is a BVH).
=> Add various utilities

src/query/intersection_test/intersection_test_cuboid_cuboid.rs, src/query/intersection_test/intersection_test_cuboid_segment.rs, src/query/intersection_test/intersection_test_cuboid_triangle.rs
At this point I think it's nitpicking but I still think it could be useful.
=> Remove unneeded comparison for 2D intersections test

src/shape/compound.rs, src/shape/trimesh.rs, src/transformation/hertel_mehlhorn.rs, src/transformation/mod.rs
Closes #62.
Again, I'm not sure how to make this accessible to the user. I've added it as a method to `TriMesh` for now, but maybe adding it as `CompoundShape::from_trimesh()` makes more sense.
=> Add Hertel-Mehlhorn algorithm

CHANGELOG.md, src/shape/compound.rs, src/transformation/ear_clipping.rs, src/transformation/hertel_mehlhorn.rs
=> `Compound::decompose_trimesh`: Remove `self` from arguments

src/transformation/utils.rs
`dr` should be `down-right` and `ur` should be `up-right` in code comment
=> Fix typo in transformation/utils.rs

src/shape/convex_polyhedron.rs
Currently only doing it on `ConvexPolyhedron` colliders, but could essentially copy paste this to the rest of the scaling.
=> Default to existing normal if can't normalize

CHANGELOG.md, crates/parry2d/examples/time_of_impact_query2d.rs, crates/parry2d/tests/geometry/ball_ball_toi.rs, crates/parry2d/tests/geometry/time_of_impact2.rs, crates/parry3d/examples/time_of_impact_query3d.rs, crates/parry3d/tests/geometry/ball_ball_toi.rs, crates/parry3d/tests/geometry/ball_triangle_toi.rs, crates/parry3d/tests/geometry/still_objects_toi.rs, crates/parry3d/tests/geometry/time_of_impact3.rs, crates/parry3d/tests/geometry/trimesh_trimesh_toi.rs, src/query/default_query_dispatcher.rs, src/query/query_dispatcher.rs, src/query/time_of_impact/mod.rs, src/query/time_of_impact/time_of_impact.rs, src/query/time_of_impact/time_of_impact_composite_shape_shape.rs, src/query/time_of_impact/time_of_impact_halfspace_support_map.rs, src/query/time_of_impact/time_of_impact_heightfield_shape.rs, src/query/time_of_impact/time_of_impact_support_map_support_map.rs, src/shape/heightfield2.rs, src/shape/heightfield3.rs, src/transformation/to_polyline/heightfield_to_polyline.rs, src/transformation/to_polyline/mod.rs
- Add to `query::time_of_impact` a boolean argument `stop_at_penetration`. If set to `false`
the linear shape-cast won’t immediately stop if the shape is penetrating another shape at its
starting point **and** its trajectory is such that it’s existing that penetration configuration.
Needed by: https://github.com/dimforge/rapier/issues/266
- Add 2D `Heightfield::to_polyline` to get the explicit vertices/indices of a 2D heightfield
seen as a polyline.
- Add the support for linear shape-cast (`query::time_of_impact`) for heightfields.
=> Improve linear shape-casting

src/shape/trimesh.rs
This could introduce bugs in the point classification.
Instead it is up to the user to provide a well-formed mesh, or add the `TriMeshFlags::DELETE_DEGENERATE_TRIANGLES` flag.
=> Don’t guard pseudo-normal generation against degenerate triangles

src/query/contact_manifolds/contact_manifold.rs, src/query/contact_manifolds/contact_manifolds_ball_ball.rs, src/query/contact_manifolds/contact_manifolds_capsule_capsule.rs, src/query/contact_manifolds/contact_manifolds_convex_ball.rs, src/query/contact_manifolds/contact_manifolds_halfspace_pfm.rs, src/query/contact_manifolds/contact_manifolds_heightfield_composite_shape.rs, src/query/contact_manifolds/contact_manifolds_heightfield_shape.rs, src/query/contact_manifolds/contact_manifolds_pfm_pfm.rs, src/query/contact_manifolds/contact_manifolds_trimesh_shape.rs, src/query/contact_manifolds/internal_edges_fixer.rs, src/query/contact_manifolds/mod.rs, src/shape/convex_polygon.rs, src/shape/convex_polyhedron.rs, src/shape/cuboid.rs, src/shape/feature_id.rs, src/shape/heightfield3.rs, src/shape/mod.rs, src/shape/polygonal_feature2d.rs, src/shape/polygonal_feature3d.rs, src/shape/polygonal_feature_map.rs, src/shape/triangle.rs, src/shape/trimesh.rs
This PR addresses the internal edges problem for 3D meshes and 3D heightfields by removing contacts that are detected as invalid because they happen at internal edges or internal vertices on a flat surface.
The solution isn’t perfect as some edge contacts may still happen if the flat surface has many small triangles (but, in this case, it is strongly recommended to simplify the mesh anyway for better performances).
=> Address the internal edges problem in 3D

src/shape/convex_polygon.rs
https://github.com/dimforge/parry/discussions/82
=> Add ConvexPolygon::offseted

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/shape/convex_polygon.rs
- Rename `AABB` to `Aabb` to comply with Rust’s style guide.
- Rename `QBVH` to `Qbvh` to comply with Rust’s style guide.
- Add `ConvexPolygon::offseted` to dilate a polygon.
- Add `CudaTriMesh` and `CudaTriMeshPtr` for triangle-meshes usable with CUDA.
- Add a no-std implementation of point-projection on a triangle mesh.
- Fix ghost collisions on internal edges on flat 3D meshed and flat 3D heightfields.
- Fix pseudo-normals calculation that could generate invalid normals for triangles with
some small vertex angles.
- Fix `Aabb::bounding_sphere` which returned a bounding sphere that was too big.
=> Release v0.11.0

CHANGELOG.md, src/bounding_volume/simd_aabb.rs, src/partitioning/mod.rs, src/partitioning/qbvh/build.rs, src/partitioning/qbvh/mod.rs, src/partitioning/qbvh/qbvh.rs, src/partitioning/qbvh/traversal.rs, src/partitioning/qbvh/traversal_no_std.rs, src/partitioning/qbvh/update.rs, src/shape/trimesh.rs
This adds `Qbvh::remove`, `Qbvh::pre_update_or_insert`, `Qbvh::refit`, `Qbvh::rebalance` to allow modifying a `Qbvh` without having to rebuild it completely.
=> Add the ability to modify a Qbvh after its creation.

src/utils/segments_intersection.rs
Point-intersection only has only one intersection point, so the original doc comments "Location of the first intersection point on the first segment." and Location of the second intersection point on the second segment" are confusing. It seems like they were copied from the Segment-intersection where those descriptions make sense.
=> Clarify doc comments of SegmentsIntersection::Point

src/partitioning/qbvh/qbvh.rs
There is no reason to take a mutable reference here.
=> Make `Qbvh::leaf_data` non-mut.

src/shape/triangle.rs
=> Fix Triangle::contains_point

.github/workflows/parry-ci-build.yml, CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml
- `Qbvh::leaf_data` now requires `&self` instead of `&mut self`.
- Replace the `Qbvh::leaf` boolean by a bitflags.
- Add `Qbvh::remove`, `Qbvh::pre_update_or_insert`, `Qbvh::refit`, `Qbvh::rebalance` to allow modifying a `Qbvh`
without having to rebuild it completely.
- Add `QbvhNode::is_leaf` to get if a node is a leaf or not.
- Add `SharedShape::trimesh_with_flags` for building a trimesh with specific pre-processing flags.
- Fix `Triangle::contains_point`.
=> Release v0.12

crates/parry3d/tests/geometry/mod.rs, crates/parry3d/tests/geometry/trimesh_intersection.rs, src/query/mod.rs, src/query/split/mod.rs, src/query/split/split.rs, src/query/split/split_trimesh.rs, src/shape/polyline.rs
Adds functionality to intersect a intersect a `TriMesh` with a plane, extracting any `Polyline`s that lie on the intersection. The API intentionally mimics the `TriMesh` split functions, and much of the implementation is identical.
- Added `TriMesh::canonical_intersection_with_plane` for intersecting with planes aligned with one of the axes
- Added `TriMesh::intersection_with_plane` for intersecting with arbitrary planes
- Added `TriMesh::intersection_with_local_plane` for intersecting with arbitrary planes in the same space as the mesh
- Added `IntersectResult` as the output type for the above functions. (Mimicing the API of the splitting functions.)
- Added `Polyline::extract_connected_components`, which splits a compound polyline into its connected components.
- I wasn't sure if unit …
=> Add functionality to intersect a `TriMesh` with a plane

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml
- About `rkyv` support: most POD structs (`Aabb`, `Ball`, `Cuboid`, etc.) are now archived as themselves instead of
being archived as different types (for example `Aabb` is archived as `Aabb` itself istead of `ArchivedAabb`).
- In 3D, add `transformation::try_convex_hull` for a convex hull calculation that will return an error instead of
panicking on unsupported inputs.
- Fixed duplicate faces in the connected components returned by `TriMesh::connected_components`.
=> Release v0.13.0

src/query/contact_manifolds/contact_manifolds_pfm_pfm.rs, src/shape/convex_polyhedron.rs, src/shape/polygonal_feature_map.rs
Fix https://github.com/dimforge/rapier/issues/417
Fix https://github.com/dimforge/rapier/issues/455
=> Fix collision-detection regression with convex polyhedron caused by the internal edges handling

src/query/intersection_test/intersection_test_composite_shape_shape.rs, src/query/intersection_test/mod.rs
The intersection check was using a distance-based best-first search that could degenerate in a complete tree traversal if there is no intersection. This PR switches to simple intersection-based depth-first search.
=> Improve performance of intersection test on composite shapes

src/query/intersection_test/intersection_test_composite_shape_shape.rs, src/query/intersection_test/mod.rs
This re-adds `IntersectionCompositeShapeShapeBestFirstVisitor` that was removed by #133. It’s marked as deprecated to avoid a breaking change just now.
=> Re-add IntersectionCompositeShapeShapeBestFirstVisitor

src/bounding_volume/simd_aabb.rs
This code:
```
use nalgebra::Isometry2;
use parry2d::shape::{SharedShape};
fn main() {
let c = SharedShape::compound(
vec![
(Isometry2::default(), SharedShape::cuboid(5.0,5.0))
]
);
let s = serde_yaml::to_string(&c).unwrap();
let c = serde_yaml::from_str::<SharedShape>(&s).unwrap();
let s2 = serde_yaml::to_string(&c).unwrap();
assert_eq!(s, s2);
}
```
Throws
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("qbvh.nodes[0].simd_aabb: invalid type: map, expected two arrays containing at least 16 floats", line: 23, column: 7)', crates/parry2d/examples/serde.rs:11:53
stack backtrace:
0: rust_begin_unwind
at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
1: core::panicking::panic_fmt
at …
```
=> Make SimdAabb deserializable in map-like formats like JSON, YAML

crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/partitioning/qbvh/update.rs, src/partitioning/qbvh/update/tests.rs
One should fix #136, https://github.com/dimforge/rapier/issues/450, need confirmations. 
The other one fixes a bug that is detected by check_topology.
In addtion, the randomized tester should detect potential future problem with qbvh update.
=> Fix two bugs that would cause qbvh increment update to panic, and adding a few test cases for qbvh update

crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml
This is an automatically-generated PR to update plain HTTP links in Cargo.toml
If there are any issues with this, you can reach out to @/Benjins on Github who is the original author of this automated PR
In file `crates/parry2d-f64/Cargo.toml`:
- `http://parry.rs` was updated. The HTTP version redirects to HTTPS, but does not enforce HSTS
- `http://parry.rs/docs` was updated. The HTTP version redirects to HTTPS, but does not enforce HSTS
In file `crates/parry3d-f64/Cargo.toml`:
- `http://parry.rs` was updated. The HTTP version redirects to HTTPS, but does not enforce HSTS
- `http://parry.rs/docs` was updated. The HTTP version redirects to HTTPS, but does not enforce HSTS
In file `crates/parry2d/Cargo.toml`:
- `http://parry.rs` was updated. The HTTP version redirects to HTTPS, but does not …
=> Upgrade http links to https in Cargo.toml

README.md
The readme calls the Parry docs Rapier instead of Parry
=> Update README.md mistake

src/bounding_volume/aabb.rs, src/bounding_volume/bounding_sphere.rs, src/mass_properties/mass_properties.rs, src/partitioning/qbvh/qbvh.rs, src/query/contact/contact.rs, src/query/point/point_query.rs, src/query/ray/ray.rs, src/shape/capsule.rs, src/shape/cone.rs, src/shape/convex_polyhedron.rs, src/shape/cuboid.rs, src/shape/cylinder.rs, src/shape/feature_id.rs, src/shape/half_space.rs, src/shape/heightfield3.rs, src/shape/segment.rs, src/shape/tetrahedron.rs, src/shape/triangle.rs, src/shape/trimesh.rs, src/utils/sdp_matrix.rs
The `CheckBytes` trait was supposedly implemented with the `archive(check_bytes)` derive. It turns out this is incompatible (a no-op) when `archive(as = "Self")` is specified.
=> feat: properly implement CheckBytes for as=Self rkyv types

crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml
This removes the usage of `syn` v1 as it updated to using v2.
=> deps: Update `num-derive` from `0.3` to `0.4`.

.github/workflows/parry-ci-build.yml
These are generating warnings about using deprecated stuff within the GitHub Actions UI.
In particular, the `actions-rs/toolchain` hasn't been maintained in some time.
=> ci: Update actions.

src/partitioning/qbvh/update.rs, src/query/contact_manifolds/contact_manifold.rs, src/query/contact_manifolds/contact_manifolds_composite_shape_composite_shape.rs, src/query/contact_manifolds/contact_manifolds_composite_shape_shape.rs, src/query/contact_manifolds/contact_manifolds_halfspace_pfm.rs, src/query/contact_manifolds/contact_manifolds_heightfield_composite_shape.rs, src/query/contact_manifolds/contact_manifolds_heightfield_shape.rs, src/shape/trimesh.rs, src/transformation/convex_hull3/convex_hull.rs
When replacing something with the default value, can juse use `take` instead.
=> clippy: Fix mem_replace_with_default.

src/query/split/split_trimesh.rs
When computing plane intersection with a lot of trimeshes with `intersection_with_plane`, I sometimes get an exception:
```
thread 'Async Compute Task Pool (2)' panicked at 'assertion failed: idx_a <= index_adjacencies.len()', parry/crates/parry3d/../../src/query/split/split_trimesh.rs:423:13
stack backtrace:
0:        0x10174e024 - std::backtrace_rs::backtrace::libunwind::trace::h77b39d3188241b9b
at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
1:        0x10174e024 - std::backtrace_rs::backtrace::trace_unsynchronized::h255fc0d6f6a27160
at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2:        0x10174e024 - …
```
=> intersection_with_plane: insert adjacencies in the correct order

src/transformation/voxelization/voxelized_volume.rs
square flat shapes cause the voxel dimensions to be miscalculated and allocate vastly more voxels than intended. see [v-hacd latest](https://github.com/kmammou/v-hacd/blob/454913fad7d4071f374e3d9aee3e6ccc98bca84d/include/VHACD.h#L5113)
=> Fix voxel dim calc

src/query/contact_manifolds/contact_manifolds_convex_ball.rs
When a ball's origin lay directly on a surface, no contact was found. While the contact normal is ambiguous in this case, we can make up something plausible.
This was causing me considerable confusion in some unit tests, where trivially intersecting ball-triangle tests were failing with contact manifolds.
=> Fix ball-convex manifolds missing contacts in corner cases

src/mass_properties/mass_properties.rs, src/partitioning/qbvh/mod.rs, src/shape/triangle.rs
Fix https://github.com/dimforge/rapier/issues/186
=> doc: specifiy that inv_principal_inertia_sqrt is calculated relative to the center of mass

CHANGELOG.md, src/partitioning/qbvh/update.rs
In many situations (see linked issues), especially at the first simulation frame, but also if many object are inserted at once during the simulation, the QBVH incremental update algorithm could lead to a degenerate tree. Ideally the fix would improve the incremental update to lower risks of imbalance, but this is a very difficult problem.
A way simpler, but less efficient, fix (that is implemented in this PR) is to force a complete tree rebuild if it reaches a certain depth, indicating degeneracy. That depth is set to 15, which for a perfectly balanced QBVH, can hold `4^15 = 1.073.741.824` leaves (meaning that past that number of object in the tree you are guaranteed to trigger a forced rebuild at every update. But this is a very unlikely number to reach in practical games).
Fix …
=> fix: force a complete QBVH rebuild when it gets too imbalanced.

src/query/ray/ray.rs, src/query/ray/ray_support_map.rs
Many shapes like cylinders, cones, capsules, convex polyhedra, and convex polygons use support mapping and a variant of GJK for ray casting.
If the ray origin is inside of the shape and the shape is marked as non-solid (i.e. hollow), the ray casting method shifts the ray origin just outside of the shape and reverses the ray's direction before running GJK a second time. This acts as a way to find the hit point on the boundary as if the ray was to keep travelling inside the shape.
However, the actual final ray cast is still done from the *outside* of the shape, and the normal ends up pointing *outward*. This is *not* the expected result, as the specialized ray casting implementations for shapes like circles, rectangles, triangles, and so on return the normal pointing in the *interior* of …
=> Fix normal direction for GJK ray casting inside non-solid shapes

src/shape/compound.rs, src/shape/polyline.rs, src/shape/shape.rs, src/shape/shared_shape.rs, src/shape/trimesh.rs
Based on this issue in rapier: https://github.com/dimforge/rapier/issues/577
I implemented Debug for SharedShape by using the trait method to get the ShapeType, and then using that as the basis of the debug info. 
This is my first PR, I hope it's ok! I will post a corresponding one to rapier.
=> add a Debug impl for SharedShape

CHANGELOG.md, crates/parry2d/tests/geometry/aabb_scale.rs, crates/parry2d/tests/geometry/mod.rs, crates/parry3d/tests/geometry/aabb_scale.rs, crates/parry3d/tests/geometry/mod.rs, src/bounding_volume/aabb.rs, src/bounding_volume/mod.rs
I wrote the function that would allow for an `aabb` to be scaled with respect to its centre instead of the origin ( Issue #155 ). I added a unit test as a sanity check that this was doing the right thing, but not anything comprehensive.
=> Aabb wrt centre/issue #155

src/shape/tetrahedron.rs
When reading [docs about the `parry3d::shape::Tetrahedron` struct](https://docs.rs/parry3d/latest/parry3d/shape/struct.Tetrahedron.html) I noticed that the `Tetrahedron`'s `new()` method had the following description:
> Creates a tetrahedron from three points.
This PR fixes that oversight (and some others).
=> Fix some docstrings in `tetrahedron.rs`

src/shape/convex_polygon.rs
I'm constantly running into panics, due to
```
parry2d-0.13.5\src\shape\convex_polygon.rs:185:59:
index out of bounds: the len is 2 but the index is 2
```
This occurs more often than _normally_ (I assume), because I create compound shapes at runtime after deforming objects into smaller ones.
It should not be possible to create a polygon that has less than 3 points. Also, it should be ensured that no empty points is passed. That fixes another crash where `normals[0]` indexes points that don't exist.
=> Ensure convex polygon does not panic due to invalid amount of points

crates/parry2d/tests/query/mod.rs, crates/parry2d/tests/query/point_composite_shape.rs, src/query/point/point_composite_shape.rs
Fixes the issue in 2D where `project_local_point_and_get_feature` of `TriMesh` would NOT return a triangle enclosing the point. This can happen when two triangles share an edge and that edge is closest to the query point.
This can happen because `project_local_point_and_get_feature` does not treat `TriMesh` as solid. However, in 2D TriMeshes can be treated as solid.
This change introduced by this PR is a subtly breaking change, because earlier versions would project to one of the edges.
I think breaking this API "contract" is reasonable, because the earlier behavior was misleading, with the returned `PointProjection` telling that the point was not inside and the feature id being incorrect, and always being set to a Face variant anyway.
=> Treat TriMesh as solid in project_local_point_and_get_feature with dim2

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml
- Add `ShapeCastOptions` that includes two new options for (linear) shape-casting.
`ShapeCastOptions::target_distance` which will return a hit as soon as the moving
shapes are closer than this distance; and `compute_impact_geometry_on_penetration`
which forces the calculation of proper witness points and normals even if the shapes
are initially intersecting (`time_of_impact == 0.0`).
This version modifies many names related to shape-casting:
- Renamed `TOI` to `ShapeCastHit`.
- Renamed `TOIStatus` to `ShapeCastStatus`.
- Rename `RayIntersection::toi` to `RayIntersection::time_of_impact`.
- More generally, all occurrences of the word `toi` have been replaced by `time_of_impact`
for better clarity.
- Rename `query::time_of_impact` to `query::cast_shapes`. More generally, all the
functions …
=> Release v0.15.0

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/query/contact_manifolds/contact_manifolds_convex_ball.rs, src/utils/consts.rs
This replaces the heuristic based on angle by a ray-cast activated only when a normal correction happened.
=> Fix a regression in ball vs. convex shape contact manifold calculation.

crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/lib.rs, src/partitioning/qbvh/qbvh.rs, src/shape/heightfield3.rs, src/shape/trimesh.rs
This also removes an old style macro_use / extern crate for bitflags and makes all uses use the same syntax.
=> deps: Update to bitflags 2.x

src/mass_properties/mass_properties.rs
Some users hit cases where the threshold resulted in a zero inverse inertia tensor for life-sized thin objects. This PR removes the threshold and only clamp the negative principal inertia values.
=> fix: remove threshold in angular inertia eigenvalue calculation

crates/parry2d/tests/geometry/time_of_impact2.rs, src/query/shape_cast/shape_cast_ball_ball.rs
This PR fixes a bug where `cast_shapes_ball_ball` ignored the `stop_on_penetration` flag and always returned a hit for separating intersecting balls.
=> Respect stop_on_penetration flag in ball-ball shape casting

src/query/epa/epa3.rs
An debug-log is preferable to a random panic in mathematical code.
Related to #202
=> fix: don’t panic in EPA

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml
- Fix edge case where some of the principal angular inertia are clamped to zero
for decimeter-sized objects.
- Have ball-ball shape casting take into account the `stop_on_penetration` flags.
- Don’t panic in EPA for a corner case that needs some additional debugging. Show a debug log instead.
- Implement concave polygons intersections: `polygons_intersection_points`, `polygon_intersection`.
- Update `bitflags` to version ^2.3
- Update `nalgebra` to 0.33.
- Update `indexmap` to 2.
=> Release v0.16.0

CHANGELOG.md, src/transformation/mesh_intersection/mesh_intersection.rs, src/utils/mod.rs, src/utils/spade.rs
The `spade` crate has restrictions on how small a denormal number can be when giving it input points. This PR sanitizes the coordinates by flushing small denormal numbers given to `spade` to 0.
=> fix: don’t crash mesh/mesh intersection if some mesh coordinates are small denormal numbers

CHANGELOG.md, src/shape/shape.rs, src/shape/shared_shape.rs
We currently have some generic logic for scaling `Shape` in `bevy_rapier`. It seems reasonable to put this in the `Shape` trait so that the same logic can be reused elsewhere.
=> Add `clone_scaled` to Shape traits

src/shape/shape.rs, src/shape/triangle.rs
Commit 4ffa010f99a38ebd6d7ac763355403e98454fc09 introduced a method that is only available with feature = "dim3", but a method that is present when feature = "dim2" was linking to it. The doc commnets referencing it must be protected by `cfg_attr` checks.
=> Fix rustdoc error in `Triangle`.

.github/workflows/parry-ci-build.yml, src/shape/shape.rs
This doesn't use nightly (like docs.rs does) because there are other warnings on nightly builds that would break this.
Also, I used `parallel` here but that isn't tested yet by other build configs.
=> ci: Add `build-doc` job to test building docs.

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml
- Add `Triangle::robust_scaled_normal` and `Triangle::robust_normal` as a more robust way to compute the triangles
normal for thin triangles that generally cause numerical instabilities.
- Add `Triangle::angle_closest_to_90` to find the triangle’s vertex with an angle closest to 90 degree.
- Add the `wavefront` feature that enables `TriMesh::to_obj_file` for exporting a mesh as an obj file.
- Add `Shape::scale_dyn` for scaling a shape as a trait-object.
- `TypedShape::Custom(u32)` is now `TypedShape::Custom(&dyn Shape)`.
- `AabbSetsInterferencesCollector::tolerence` is now spelled correctly as `tolerance`.
- `Real` is now exposed through a `use` statement,
so that an indirection is removed in documentation:
previous occurrences of `Real` now show `f32` or `f64`.
- Significantly improved …
=> Release v0.17.0

src/bounding_volume/aabb.rs, src/query/gjk/gjk.rs, src/shape/polyline.rs
=> Fix `clippy::doc_lazy_continuation` lints

Cargo.toml, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml
This will add a one line warning from `cargo` until 1.80 (which is due for release soon).
=> Fix `unexpected_cfgs` warnings

crates/parry3d/Cargo.toml, crates/parry3d/examples/plane_intersection.rs
- a visual helper relevant to #248
[Screencast from 08-05-2024 06:05:14 PM.webm](https://github.com/user-attachments/assets/15ad87bc-9fba-4d1a-8e9c-da5c695dc5c8)
=> add an example for intersection plane

CHANGELOG.md, crates/parry2d/Cargo.toml, crates/parry2d/tests/geometry/epa_convergence.rs, crates/parry2d/tests/geometry/mod.rs, crates/parry3d/Cargo.toml, crates/parry3d/examples/plane_intersection.rs, src/query/epa/epa2.rs, src/query/epa/epa3.rs, src/query/gjk/gjk.rs, src/query/gjk/voronoi_simplex2.rs
Improves converges by checking if it's stuck. In such a case return a result, as a better solution will not be found, and most likely they are intersecting but not within the EPS.
Also decrease max iterations from 10000 to 100. It usually converges in 4-5 iterations, no need to ever do as many. Also we never really want a precision that big, we are ok with a lower precision most times.
- Fixes https://github.com/dimforge/parry/issues/205
Possibly fixes:
- https://github.com/dimforge/parry/issues/157
=> Improve convergence of epa algorithm in case it's stuck

.github/workflows/parry-ci-build.yml, crates/parry3d/Cargo.toml, crates/parry3d/benches/all.rs, crates/parry3d/benches/bounding_volume/mod.rs, crates/parry3d/benches/common/default_gen.rs, crates/parry3d/benches/common/generators.rs, crates/parry3d/benches/common/macros.rs, crates/parry3d/benches/query/contacts.rs, crates/parry3d/benches/query/ray.rs, crates/parry3d/benches/support_map/mod.rs
Fixes compiling for parry benchmarks
There has been a few API changes since their creation, especially around `ConvexHull`, and in a lesser amount `Capsule`.
=> Parry benchmarks compilation

.github/workflows/parry-ci-build.yml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/transformation/mesh_intersection/mesh_intersection.rs, src/transformation/mod.rs, src/transformation/wavefront.rs
- Follow up to https://github.com/dimforge/parry/pull/258
=> Fix wavefront tests + new test for different pos + add them in ci

CHANGELOG.md, src/transformation/mesh_intersection/mesh_intersection.rs, src/transformation/mesh_intersection/mesh_intersection_error.rs, src/transformation/mesh_intersection/mod.rs, src/transformation/mesh_intersection/triangle_triangle_intersection.rs, src/transformation/mod.rs, src/transformation/polygon_intersection.rs
This PR further improves the robustness the mesh/mesh intersection for a better handling of pars of meshes with coplanar triangles. This was motivated by the need to fix a case where the same mesh would be cut multiple times by the exact same second mesh. All cuts except for the first one result in degenerate cases where many triangles are coplanar.
This applies the following changes:
- Fix an issue where the orientation of a triangle output by the convex-polygons intersection algorithm, when given one triangle fully inside the other, is incorrect.
- Fix an issue where coplanar triangles could be output twice by the mesh/mesh intersection code.
- Improve robustness of convex-polygons intersection by avoiding the incorrect in-out state to be set when traversing an ambiguous configuration …
=> Improve robustness of mesh/mesh intersection

.github/workflows/parry-ci-build.yml, src/utils/fx_hasher.rs, src/utils/hashmap.rs, src/utils/hashset.rs, src/utils/mod.rs
- Fix #269 
Note that I'm not very comfortable with those hashers and determinism in general, I'd be more comfortable with some unit tests around it.
=> Deterministic HashSet

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/shape/trimesh.rs
This will be backported to the 0.17.x branch and released as version 0.17.4.
- Add `TriMeshConnectedComponents::to_meshes` and `::to_mesh_buffers` to easily extract individual meshes from the set
of connected components.
- Add `TriMesh::connected_component_meshes` to get the connected components as meshes directly.
- Connected-components extraction will never fail now, and no longer require the successful calculation of the mesh’s
half-edge topology.
=> feat: make connected component calculation infaillible + add helper functions

CHANGELOG.md, crates/parry2d/examples/point_in_poly2d.rs, src/shape/trimesh.rs, src/transformation/mesh_intersection/mesh_intersection.rs, src/utils/point_in_poly2d.rs
- Fix some edge-cases in `point_in_poly2d` for self-intersecting polygons.
- Fix some edge-cases in mesh/mesh intersection that could result in degenerate triangles being generated.
=> More mesh/mesh intersection and point-in-poly fixes

src/query/intersection_test/intersection_test_composite_shape_shape.rs
- Follow up to https://github.com/dimforge/parry/pull/273#issuecomment-2496130758 ; Thanks @wlinna!
=> IntersectionCompositeShapeShapeVisitor is now able to return partId

CHANGELOG.md, src/shape/trimesh.rs
The connected-components extraction from topology would occasionally result in a crash when generating the individual meshes if two partitions of the connectivity graph only share a single vertex. The union-find version of mesh extraction does not suffer from this issue.
=> fix: always compute mesh connected-components from union-find

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml
- Implement `::to_trimesh` in 2d for `Cuboid` and `Aabb`.
- Fix some edge-cases in `point_in_poly2d` for self-intersecting polygons.
- Fix some edge-cases in mesh/mesh intersection that could result in degenerate triangles being generated.
- Propagate error information while creating a mesh and using functions making use of it (See #262):
- `TriMesh::new`
- `TriMesh::intersection_with_aabb`
- `SharedShape::trimesh`
- `SharedShape::trimesh_with_flags`
- `point_cloud_bounding_sphere` and `point_cloud_bounding_sphere_with_center` now returns a `BoundingSphere`.
- Removed `IntersectionCompositeShapeShapeBestFirstVisitor` (which had been deprecated for a while):
use `IntersectionCompositeShapeShapeVisitor` instead.
=> Release v0.18.0

src/query/default_query_dispatcher.rs
This was causing shapecasts against heightfields to fall through to Unsupported, if and only if the heightfield was in the second position
=> Fix shape-heightfield shape cast

crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml
This brings `no_std` support, so this is now able to be used in a `no_std` context, so always build it, but enable `std` support when building parry for `std`.
=> Update `thiserror` to 2.x

CHANGELOG.md, src/transformation/vhacd/parameters.rs
This is to make something in Rapier be able to impl `Copy`.
=> Derive `Copy` for `VHACDParameters`

CHANGELOG.md, src/shape/convex_polygon.rs, src/shape/shared_shape.rs
- Fixes https://github.com/dimforge/parry/issues/277
In Godot Rapier, Godot sends vertices that it uses to draw the polygon. If Parry removes some vertices, then the physics will not work correct. We need the extra vertices even if collinear, and ideally have the collinearity check done in Godot at some point or sent as a warning to console. For now a function that accepts points and doesn't remove any is needed for this use case.
=> Create constructor for ConvexPolyline that does not remove any vertices

CHANGELOG.md, src/mass_properties/mass_properties.rs
Parry's formula for the 3D shifted angular inertia tensor is wrong, causing compound shapes with offsets to have an incorrect angular inertia. This results in wonky behavior in physics engines such as Rapier and Avian.
An example of this: A 1x3x1 cuboid collider in bevy_rapier3d has a principal angular inertia of `[2.5, 0.5, 2.5]`. However, a compound collider of three 1x1x1 cubes stacked on top of each other has a principal angular inertia of `[2.5, 4.5, 2.5]`.
Spawning dynamic bodies for the two colliders with a slight rotation about the x axis and some initial angular velocity, this results in the following behavior:
https://github.com/user-attachments/assets/0bcc9cc4-10ed-467b-9907-a85b6092f5f8
The 1x3x1 cuboid spins a bit at the start, falls on its side, and goes to rest quickly, …
=> Fix wrong sign in `MassProperties::construct_shifted_inertia_matrix`

CHANGELOG.md, src/query/point/point_composite_shape.rs, src/query/split/split_trimesh.rs, src/shape/trimesh.rs, src/transformation/mesh_intersection/mesh_intersection.rs
Currently, enabling the `TriMeshFlags::FIX_INTERNAL_EDGES` flag on a `TriMesh` would automatically enable the `ORIENTED` flag too. This is problematic because some users (on rapier in particular) want to enable  `FIX_INTERNAL_EDGES` on open meshes. While this is technically valid, the implied `ORIENTED` flag results in some incorrect collision-detection between mesh and balls due to the malformed interior of these open meshes.
This PR decouples both flags so that `FIX_INTERNAL_EDGES` can be specified without having an impact on point projection.
=> feat: decouple the FIX_INTERNAL_EDGES from the ORIENTED trimesh flags

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/bounding_volume/aabb.rs, src/query/gjk/gjk.rs, src/query/query_dispatcher.rs
- Derive `Copy` for `VHACDParameters`.
- Add `spade` default feature for algorithms using Delaunay triangulation from `spade`.
- Add `SharedShape::from_convex_polyline_unmodified` and `ConvexPolygon::from_convex_polyline_unmodified`
to initialize a polyline from a set of points assumed to be convex, and without modifying this set even
if some points are collinear.
- Add `TriMesh::pseudo_normals_if_oriented` that returns `Some` only if the mesh has the `TriMeshFlags::ORIENTED`
flag enabled.
- The `TriMeshFlags::FIX_INTERNAL_EDGES` flag no longer automatically enable the `TriMeshFlags::ORIENTED`
flag (but the mesh pseudo-normals will still be computed).
- Improve `no_std` compatibility.
- Everything is now compatible, except `mesh_intersections`, `split_trimesh`,
convex hull validation, and …
=> Release v0.19.0

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/query/contact_manifolds/contact_manifolds_voxels_ball.rs, src/query/contact_manifolds/contact_manifolds_voxels_shape.rs, src/query/ray/ray_voxels.rs, src/shape/shape.rs, src/shape/voxels.rs
- Added the `Voxels` type: a dedicated shape for voxel models. This is currently experimental because some features are
still missing (in particular: shape-casting, mass properties, and collision-detection against non-convex shapes).
- Added `SharedShape::voxels`, `SharedShape::voxels_from_points`, and `::voxelized_mesh` for creating a voxels shape
from grid coordinates, points, or automatic voxelization of a triangle mesh.
=> Release v0.20.0

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/bounding_volume/aabb_voxels.rs, src/bounding_volume/bounding_sphere_voxels.rs, src/partitioning/qbvh/qbvh.rs, src/query/contact_manifolds/contact_manifolds_voxels_ball.rs, src/query/contact_manifolds/contact_manifolds_voxels_shape.rs, src/query/default_query_dispatcher.rs, src/query/nonlinear_shape_cast/mod.rs, src/query/nonlinear_shape_cast/nonlinear_shape_cast_voxels_shape.rs, src/query/point/point_voxels.rs, src/query/ray/ray_voxels.rs, src/query/shape_cast/mod.rs, src/query/shape_cast/shape_cast_voxels_shape.rs, src/shape/mod.rs, src/shape/shared_shape.rs, src/shape/trimesh.rs, src/shape/voxels.rs, src/transformation/to_outline/voxels_to_outline.rs, src/transformation/to_polyline/voxels_to_polyline.rs, src/transformation/to_trimesh/voxels_to_trimesh.rs
- Rework the `Voxels` shape API to use better method names.
- Added implementations for linear and non-linear shape-casting involving `Voxels` shapes.
=> feat: implement shape-casting for voxels shapes

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/shape/voxels.rs
Calling `Voxels::set_voxel` would immediately result in an infinite recursion due to a typo.
This is fixed in this PR.
=> Fix infinite loop in Voxels::set_voxel

CHANGELOG.md, src/query/mod.rs, src/query/ray/mod.rs, src/query/ray/ray_composite_shape.rs, src/query/ray/ray_trimesh.rs
This adds (in 3D only) `TriMesh::cast_ray_with_culling` and `TriMesh::cast_local_ray_with_culling` for casting rays on a triangle mesh but with the possibility to prevents hits on front-faces or back-faces.
=> feat: add trimesh raycasting that account for backface/frontface culling

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/bounding_volume/aabb.rs, src/mass_properties/mass_properties_voxels.rs, src/mass_properties/mod.rs, src/query/contact_manifolds/contact_manifolds_voxels_ball.rs, src/query/contact_manifolds/contact_manifolds_voxels_composite_shape.rs, src/query/contact_manifolds/contact_manifolds_voxels_shape.rs, src/query/contact_manifolds/contact_manifolds_voxels_voxels.rs, src/query/contact_manifolds/contact_manifolds_workspace.rs, src/query/contact_manifolds/mod.rs, src/query/default_query_dispatcher.rs, src/query/intersection_test/intersection_test_voxels_shape.rs, src/query/intersection_test/mod.rs, src/shape/mod.rs, src/shape/shape.rs, src/shape/shared_shape.rs, src/shape/voxels.rs, src/utils/hashmap.rs, src/utils/hashset.rs
- Add `TriMesh::cast_ray_with_culling` and `TriMesh::cast_local_ray_with_culling` for casting rays on a triangle mesh
but with the possibility to prevents hits on front-faces or back-faces.
- Add contact manifold calculation between two voxels shapes, or a voxels shape and compound shape.
- Add intersection check between voxels and other shapes.
- Add new variants to `TypedWorkspaceData` for voxels-voxels and voxels-compound collision detection workspace
data.
- The `Voxels` shape now only support cuboids as their leaf geometries (pseudo-balls were removed).
=> Release v0.21.0

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/query/contact_manifolds/contact_manifolds_voxels_shape.rs, src/shape/shared_shape.rs, src/shape/voxels.rs
It is not unusual for games to split their voxels world into multiple chunks, e.g., to differentiate between voxels of different types. however, than chunking can result in internal edges being created at the interface between two chunks.
This PR adds some helper functions for letting the user specify manually which pair of `Voxels` shapes are interfacing at their boundaries, to update their internal state accordingly.
=> feat: implement cross-Voxels internal edges handling

CHANGELOG.md, src/query/clip/clip_aabb_line.rs
Improves #310
<details><summary>Edits</summary>
<p>
- I ([Thierry](https://github.com/Vrixyz)) changed the description to "improves", as linked issue contains different errors and I don't want this PR to close the issue automatically if merged. (See https://github.com/dimforge/parry/pull/358)
</p>
</details>
=> Fix #310: Matrix index out of bounds.

CHANGELOG.md, src/query/ray/ray_support_map.rs, src/shape/segment.rs
=> Fix zero length 2d segment raycast

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/partitioning/bvh/bvh_tree.rs
This fixes a an incorrect BVH state that could be reached if a partial root is created after removing one of the remaining two leaves.
=> fix BVH leaf node index update after a removal that results in a partial root

src/partitioning/bvh/bvh_traverse.rs, src/query/contact_manifolds/contact_manifolds_composite_shape_composite_shape.rs, src/query/contact_manifolds/contact_manifolds_composite_shape_shape.rs, src/query/contact_manifolds/contact_manifolds_heightfield_composite_shape.rs, src/query/contact_manifolds/contact_manifolds_heightfield_shape.rs, src/query/contact_manifolds/contact_manifolds_trimesh_shape.rs, src/query/contact_manifolds/contact_manifolds_voxels_composite_shape.rs, src/query/contact_manifolds/contact_manifolds_voxels_shape.rs, src/query/contact_manifolds/contact_manifolds_voxels_voxels.rs, src/query/contact_manifolds/contact_manifolds_workspace.rs, src/shape/heightfield3.rs, src/shape/shape.rs
Current `master` has [warnings on nightly](https://github.com/dimforge/parry/actions/runs/16371307515/job/46260101976) due to a bunch of `mismatched_lifetime_syntaxes`:
```rs
warning: lifetime flowing from input to output with different syntax can be confusing
--> crates/parry3d/../../src/partitioning/bvh/bvh_traverse.rs:79:44
|
79 |     pub fn leaves<F: Fn(&BvhNode) -> bool>(&self, check_node: F) -> Leaves<F> {
|                                            ^^^^^                    --------- the lifetime gets resolved as `'_`
|                                            |
|                                            this lifetime flows to the output
|
= note: `#[warn(mismatched_lifetime_syntaxes)]` on by default
help: one option is to remove the lifetime for references and use the …
```
=> Fix CI nightly's mismatched_lifetime_syntaxes

CHANGELOG.md, crates/parry2d-f64/Cargo.toml, crates/parry2d/Cargo.toml, crates/parry3d-f64/Cargo.toml, crates/parry3d/Cargo.toml, src/shape/voxels/voxels.rs
- The `Voxels` shape now uses a sparse storage internally.
- Remove `Voxels::try_set_voxel`. Use `::set_voxel` instead.
- The `Voxels::domain` function returns values instead of references now.
- Removed `Voxels::extents` and `Voxels::domain_center`. They can be obtained
from `Voxels::local_aabb`.
=> Release 0.25.0
